name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: bootstrap project and test it
      run: |
        yarn
        yarn test:lint
        yarn test:unit
        yarn test:build
